### ISSUE TITLE
More comprehensive approach

### ISSUE THREAD

**Issue by dandv** [goware/emailx#1]
Hey guys,

I've been looking for a more comprehensive approach to the problem of email normalization and came up with one that I believe surpasses all other attempts I've seen on GitHub.

It's a JavaScript package for Meteor, https://github.com/iDoRecall/email-normalize

Works for:

* `gmail.com`, `googlemail.com` and `google.com` - the [only domains Google is known to use for incoming email](https://en.wikipedia.org/wiki/List_of_Google_domains)
* Any domain [hosted with Google Apps for Work](https://en.wikipedia.org/wiki/Google_Apps_for_Work#Gmail)
* FastMail and [domains hosted with FastMail](https://www.fastmail.com/help/receive/domains.html)
* Microsoft's outlook.com, hotmail.com, live.com
* Yahoo! domains

PRs welcome.

**Comment by VojtechVitek** [comment]
Hi @dandv,
thanks for your feedback.

We didn't want to go the "comprehensive" way, see our [README](https://github.com/goware/emailx/blob/master/README.md).

btw: Wiping out `.` or `+` characters from email name is against the RFC specs. Yes, it probably resolves duplicates for you, but it also disables people from actually using their real email aliases (for easier filtering), like `example+foo@gmail.com`.

**Comment by dandv** [comment]
> Yes, it probably resolves duplicates for you, but it also disables people from actually using their real email aliases (for easier filtering), like example+foo@gmail.com.

On the contrary, we recommend giving priority to the user's preferred email - see https://github.com/iDoRecall/email-normalize#notes
