### ISSUE TITLE
Validate checks userDotRegexp, but FastValidate does not

### ISSUE THREAD

**Issue by amariampolskiy** [goware/emailx#4]
As per subject. FastValidate misses some incorrectly formatted emails that Validate catches. I think it shouldn't be so.

**Comment by VojtechVitek** [comment]
send a PR and we can discuss :) thanks

**Comment by amariampolskiy** [comment]
Here you go https://github.com/goware/emailx/pull/5

**Comment by VojtechVitek** [comment]
Fixed in #5
